select
    md5(concat_ws('|', bet_record_key, coalesce(total_payout_amount::text, ''))) as payout_record_key,
    bet_record_key,
    bet_business_key,
    event_key,
    customer_key,
    source_file,
    source_refid,
    source_uuid,
    ticket_no,
    bookmaker_name,
    bet_placed_at,
    event_scheduled_at,
    event_category,
    venue_name,
    venue_state_code,
    race_number,
    runner_number,
    runner_name,
    customer_name,
    paid_status,
    is_cancelled,
    is_refunded,
    is_duplicate_bet_key,
    win_result,
    place_result,
    win_payout_amount,
    place_payout_amount,
    total_payout_amount
from {{ ref('fct_bets') }}
where coalesce(total_payout_amount, 0) <> 0
