xid_go:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST', 'localhost') }}"
      user: "{{ env_var('PGUSER', 'xid_user') }}"
      password: "{{ env_var('PGPASSWORD', 'xid_password') }}"
      port: "{{ env_var('PGPORT', '5432') | as_number }}"
      dbname: "{{ env_var('PGDATABASE', 'xid_go') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
